import type { Metadata } from "next";
import { Heebo, Inter, Poppins } from "next/font/google";

import "./globals.css";

import Footer from "./_layout-resources/Footer";
import Nav from "./_layout-resources/Nav/Nav";

const poppins = Poppins({ variable: "--font-poppins", weight: ["400", "500", "600", "700"], subsets: ["latin"] });
const heebo = Heebo({ variable: "--font-heebo", subsets: ["latin"], weight: ["400", "500", "600", "700"] });
const inter = Inter({ variable: "--font-inter", subsets: ["latin"], weight: ["400", "500", "600", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} ${heebo.variable} ${inter.variable} font-heebo antialiased`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
